[package]
name = "dogfood"
version = "0.1.0"
edition = "2021"

[dependencies]
markdown = "0.3.0"
regex = "1.7.3"
serde = { version = "1.0.159", features = ["derive"] }
unreact = { version = "0.5.2", default-features = false }

[features]
default = ["unreact/watch"]
